global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: [ "api-gateway:8080" ]

  - job_name: "trip-service"
    static_configs:
      - targets: [ "trip-service:2112" ]

  - job_name: "rider-service"
    static_configs:
      - targets: [ "rider-service:2112" ]

  - job_name: "driver-service"
    static_configs:
      - targets: [ "driver-service:2112" ]

  - job_name: "payment-service"
    static_configs:
      - targets: [ "payment-service:2112" ]
