// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: transport.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripDetailsRequest) Reset() {
	*x = TripDetailsRequest{}
	mi := &file_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripDetailsRequest) ProtoMessage() {}

func (x *TripDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripDetailsRequest.ProtoReflect.Descriptor instead.
func (*TripDetailsRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

func (x *TripDetailsRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type TripDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideFare      int64                  `protobuf:"varint,1,opt,name=ride_fare,json=rideFare,proto3" json:"ride_fare,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripDetailsResponse) Reset() {
	*x = TripDetailsResponse{}
	mi := &file_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripDetailsResponse) ProtoMessage() {}

func (x *TripDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripDetailsResponse.ProtoReflect.Descriptor instead.
func (*TripDetailsResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{1}
}

func (x *TripDetailsResponse) GetRideFare() int64 {
	if x != nil {
		return x.RideFare
	}
	return 0
}

func (x *TripDetailsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TripDetailsResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type TripHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripHistoryRequest) Reset() {
	*x = TripHistoryRequest{}
	mi := &file_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripHistoryRequest) ProtoMessage() {}

func (x *TripHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripHistoryRequest.ProtoReflect.Descriptor instead.
func (*TripHistoryRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{2}
}

func (x *TripHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TripHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trips         []*Trip                `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripHistoryResponse) Reset() {
	*x = TripHistoryResponse{}
	mi := &file_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripHistoryResponse) ProtoMessage() {}

func (x *TripHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripHistoryResponse.ProtoReflect.Descriptor instead.
func (*TripHistoryResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{3}
}

func (x *TripHistoryResponse) GetTrips() []*Trip {
	if x != nil {
		return x.Trips
	}
	return nil
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DriverProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        *Driver                `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverProfileResponse) Reset() {
	*x = DriverProfileResponse{}
	mi := &file_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverProfileResponse) ProtoMessage() {}

func (x *DriverProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverProfileResponse.ProtoReflect.Descriptor instead.
func (*DriverProfileResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{5}
}

func (x *DriverProfileResponse) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

type RiderProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rider         *Rider                 `protobuf:"bytes,1,opt,name=rider,proto3" json:"rider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiderProfileResponse) Reset() {
	*x = RiderProfileResponse{}
	mi := &file_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiderProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderProfileResponse) ProtoMessage() {}

func (x *RiderProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderProfileResponse.ProtoReflect.Descriptor instead.
func (*RiderProfileResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{6}
}

func (x *RiderProfileResponse) GetRider() *Rider {
	if x != nil {
		return x.Rider
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignupRiderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	ProfileImage  string                 `protobuf:"bytes,5,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRiderRequest) Reset() {
	*x = SignupRiderRequest{}
	mi := &file_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRiderRequest) ProtoMessage() {}

func (x *SignupRiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRiderRequest.ProtoReflect.Descriptor instead.
func (*SignupRiderRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{8}
}

func (x *SignupRiderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignupRiderRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupRiderRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupRiderRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SignupRiderRequest) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

type SignupDriverRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                 string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password              string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phone                 string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	ProfileImage          string                 `protobuf:"bytes,5,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	VerificationPhotos    []string               `protobuf:"bytes,6,rep,name=verification_photos,json=verificationPhotos,proto3" json:"verification_photos,omitempty"`
	CarModel              string                 `protobuf:"bytes,7,opt,name=car_model,json=carModel,proto3" json:"car_model,omitempty"`
	CarColor              string                 `protobuf:"bytes,8,opt,name=car_color,json=carColor,proto3" json:"car_color,omitempty"`
	CarPlate              string                 `protobuf:"bytes,9,opt,name=car_plate,json=carPlate,proto3" json:"car_plate,omitempty"`
	TransferRecipientCode string                 `protobuf:"bytes,10,opt,name=transfer_recipient_code,json=transferRecipientCode,proto3" json:"transfer_recipient_code,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SignupDriverRequest) Reset() {
	*x = SignupDriverRequest{}
	mi := &file_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupDriverRequest) ProtoMessage() {}

func (x *SignupDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupDriverRequest.ProtoReflect.Descriptor instead.
func (*SignupDriverRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{9}
}

func (x *SignupDriverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignupDriverRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignupDriverRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignupDriverRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SignupDriverRequest) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

func (x *SignupDriverRequest) GetVerificationPhotos() []string {
	if x != nil {
		return x.VerificationPhotos
	}
	return nil
}

func (x *SignupDriverRequest) GetCarModel() string {
	if x != nil {
		return x.CarModel
	}
	return ""
}

func (x *SignupDriverRequest) GetCarColor() string {
	if x != nil {
		return x.CarColor
	}
	return ""
}

func (x *SignupDriverRequest) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

func (x *SignupDriverRequest) GetTransferRecipientCode() string {
	if x != nil {
		return x.TransferRecipientCode
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{10}
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PreviewTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pickup        *Coordinate            `protobuf:"bytes,2,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Destination   *Coordinate            `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewTripRequest) Reset() {
	*x = PreviewTripRequest{}
	mi := &file_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewTripRequest) ProtoMessage() {}

func (x *PreviewTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewTripRequest.ProtoReflect.Descriptor instead.
func (*PreviewTripRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{11}
}

func (x *PreviewTripRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PreviewTripRequest) GetPickup() *Coordinate {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *PreviewTripRequest) GetDestination() *Coordinate {
	if x != nil {
		return x.Destination
	}
	return nil
}

type PreviewTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RideFares     []*RideFare            `protobuf:"bytes,1,rep,name=ride_fares,json=rideFares,proto3" json:"ride_fares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewTripResponse) Reset() {
	*x = PreviewTripResponse{}
	mi := &file_transport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewTripResponse) ProtoMessage() {}

func (x *PreviewTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewTripResponse.ProtoReflect.Descriptor instead.
func (*PreviewTripResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{12}
}

func (x *PreviewTripResponse) GetRideFares() []*RideFare {
	if x != nil {
		return x.RideFares
	}
	return nil
}

type StartTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RideFareId    string                 `protobuf:"bytes,2,opt,name=ride_fare_id,json=rideFareId,proto3" json:"ride_fare_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTripRequest) Reset() {
	*x = StartTripRequest{}
	mi := &file_transport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTripRequest) ProtoMessage() {}

func (x *StartTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTripRequest.ProtoReflect.Descriptor instead.
func (*StartTripRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{13}
}

func (x *StartTripRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartTripRequest) GetRideFareId() string {
	if x != nil {
		return x.RideFareId
	}
	return ""
}

type StartTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTripResponse) Reset() {
	*x = StartTripResponse{}
	mi := &file_transport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTripResponse) ProtoMessage() {}

func (x *StartTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTripResponse.ProtoReflect.Descriptor instead.
func (*StartTripResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{14}
}

func (x *StartTripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type InitiatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	TripRating    int64                  `protobuf:"varint,4,opt,name=trip_rating,json=tripRating,proto3" json:"trip_rating,omitempty"`
	RiderComment  string                 `protobuf:"bytes,5,opt,name=rider_comment,json=riderComment,proto3" json:"rider_comment,omitempty"`
	DriverTip     int64                  `protobuf:"varint,6,opt,name=driver_tip,json=driverTip,proto3" json:"driver_tip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePaymentRequest) Reset() {
	*x = InitiatePaymentRequest{}
	mi := &file_transport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentRequest) ProtoMessage() {}

func (x *InitiatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentRequest.ProtoReflect.Descriptor instead.
func (*InitiatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{15}
}

func (x *InitiatePaymentRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitiatePaymentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InitiatePaymentRequest) GetTripRating() int64 {
	if x != nil {
		return x.TripRating
	}
	return 0
}

func (x *InitiatePaymentRequest) GetRiderComment() string {
	if x != nil {
		return x.RiderComment
	}
	return ""
}

func (x *InitiatePaymentRequest) GetDriverTip() int64 {
	if x != nil {
		return x.DriverTip
	}
	return 0
}

type InitiatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutUrl   string                 `protobuf:"bytes,1,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiatePaymentResponse) Reset() {
	*x = InitiatePaymentResponse{}
	mi := &file_transport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiatePaymentResponse) ProtoMessage() {}

func (x *InitiatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiatePaymentResponse.ProtoReflect.Descriptor instead.
func (*InitiatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{16}
}

func (x *InitiatePaymentResponse) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

var File_transport_proto protoreflect.FileDescriptor

const file_transport_proto_rawDesc = "" +
	"\n" +
	"\x0ftransport.proto\x12\awayfare\x1a\fschema.proto\"-\n" +
	"\x12TripDetailsRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"c\n" +
	"\x13TripDetailsResponse\x12\x1b\n" +
	"\tride_fare\x18\x01 \x01(\x03R\brideFare\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"-\n" +
	"\x12TripHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\":\n" +
	"\x13TripHistoryResponse\x12#\n" +
	"\x05trips\x18\x01 \x03(\v2\r.wayfare.TripR\x05trips\",\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\x15DriverProfileResponse\x12'\n" +
	"\x06driver\x18\x01 \x01(\v2\x0f.wayfare.DriverR\x06driver\"<\n" +
	"\x14RiderProfileResponse\x12$\n" +
	"\x05rider\x18\x01 \x01(\v2\x0e.wayfare.RiderR\x05rider\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x95\x01\n" +
	"\x12SignupRiderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12#\n" +
	"\rprofile_image\x18\x05 \x01(\tR\fprofileImage\"\xd6\x02\n" +
	"\x13SignupDriverRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12#\n" +
	"\rprofile_image\x18\x05 \x01(\tR\fprofileImage\x12/\n" +
	"\x13verification_photos\x18\x06 \x03(\tR\x12verificationPhotos\x12\x1b\n" +
	"\tcar_model\x18\a \x01(\tR\bcarModel\x12\x1b\n" +
	"\tcar_color\x18\b \x01(\tR\bcarColor\x12\x1b\n" +
	"\tcar_plate\x18\t \x01(\tR\bcarPlate\x126\n" +
	"\x17transfer_recipient_code\x18\n" +
	" \x01(\tR\x15transferRecipientCode\"'\n" +
	"\fAuthResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x91\x01\n" +
	"\x12PreviewTripRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x06pickup\x18\x02 \x01(\v2\x13.wayfare.CoordinateR\x06pickup\x125\n" +
	"\vdestination\x18\x03 \x01(\v2\x13.wayfare.CoordinateR\vdestination\"G\n" +
	"\x13PreviewTripResponse\x120\n" +
	"\n" +
	"ride_fares\x18\x01 \x03(\v2\x11.wayfare.RideFareR\trideFares\"M\n" +
	"\x10StartTripRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\fride_fare_id\x18\x02 \x01(\tR\n" +
	"rideFareId\",\n" +
	"\x11StartTripResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"\xc5\x01\n" +
	"\x16InitiatePaymentRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vtrip_rating\x18\x04 \x01(\x03R\n" +
	"tripRating\x12#\n" +
	"\rrider_comment\x18\x05 \x01(\tR\friderComment\x12\x1d\n" +
	"\n" +
	"driver_tip\x18\x06 \x01(\x03R\tdriverTip\"<\n" +
	"\x17InitiatePaymentResponse\x12!\n" +
	"\fcheckout_url\x18\x01 \x01(\tR\vcheckoutUrl2\xb5\x02\n" +
	"\vTripService\x12H\n" +
	"\vPreviewTrip\x12\x1b.wayfare.PreviewTripRequest\x1a\x1c.wayfare.PreviewTripResponse\x12B\n" +
	"\tStartTrip\x12\x19.wayfare.StartTripRequest\x1a\x1a.wayfare.StartTripResponse\x12K\n" +
	"\x0eGetTripDetails\x12\x1b.wayfare.TripDetailsRequest\x1a\x1c.wayfare.TripDetailsResponse\x12K\n" +
	"\x0eGetTripHistory\x12\x1b.wayfare.TripHistoryRequest\x1a\x1c.wayfare.TripHistoryResponse2\xd5\x01\n" +
	"\rDriverService\x12N\n" +
	"\x10GetDriverProfile\x12\x1a.wayfare.GetProfileRequest\x1a\x1e.wayfare.DriverProfileResponse\x125\n" +
	"\x05Login\x12\x15.wayfare.LoginRequest\x1a\x15.wayfare.AuthResponse\x12=\n" +
	"\x06Signup\x12\x1c.wayfare.SignupDriverRequest\x1a\x15.wayfare.AuthResponse2\xd1\x01\n" +
	"\fRiderService\x12L\n" +
	"\x0fGetRiderProfile\x12\x1a.wayfare.GetProfileRequest\x1a\x1d.wayfare.RiderProfileResponse\x125\n" +
	"\x05Login\x12\x15.wayfare.LoginRequest\x1a\x15.wayfare.AuthResponse\x12<\n" +
	"\x06Signup\x12\x1b.wayfare.SignupRiderRequest\x1a\x15.wayfare.AuthResponse2f\n" +
	"\x0ePaymentService\x12T\n" +
	"\x0fInitiatePayment\x12\x1f.wayfare.InitiatePaymentRequest\x1a .wayfare.InitiatePaymentResponseB,Z*github.com/xerdin442/wayfare/shared/pkg/pbb\x06proto3"

var (
	file_transport_proto_rawDescOnce sync.Once
	file_transport_proto_rawDescData []byte
)

func file_transport_proto_rawDescGZIP() []byte {
	file_transport_proto_rawDescOnce.Do(func() {
		file_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)))
	})
	return file_transport_proto_rawDescData
}

var file_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_transport_proto_goTypes = []any{
	(*TripDetailsRequest)(nil),      // 0: wayfare.TripDetailsRequest
	(*TripDetailsResponse)(nil),     // 1: wayfare.TripDetailsResponse
	(*TripHistoryRequest)(nil),      // 2: wayfare.TripHistoryRequest
	(*TripHistoryResponse)(nil),     // 3: wayfare.TripHistoryResponse
	(*GetProfileRequest)(nil),       // 4: wayfare.GetProfileRequest
	(*DriverProfileResponse)(nil),   // 5: wayfare.DriverProfileResponse
	(*RiderProfileResponse)(nil),    // 6: wayfare.RiderProfileResponse
	(*LoginRequest)(nil),            // 7: wayfare.LoginRequest
	(*SignupRiderRequest)(nil),      // 8: wayfare.SignupRiderRequest
	(*SignupDriverRequest)(nil),     // 9: wayfare.SignupDriverRequest
	(*AuthResponse)(nil),            // 10: wayfare.AuthResponse
	(*PreviewTripRequest)(nil),      // 11: wayfare.PreviewTripRequest
	(*PreviewTripResponse)(nil),     // 12: wayfare.PreviewTripResponse
	(*StartTripRequest)(nil),        // 13: wayfare.StartTripRequest
	(*StartTripResponse)(nil),       // 14: wayfare.StartTripResponse
	(*InitiatePaymentRequest)(nil),  // 15: wayfare.InitiatePaymentRequest
	(*InitiatePaymentResponse)(nil), // 16: wayfare.InitiatePaymentResponse
	(*Trip)(nil),                    // 17: wayfare.Trip
	(*Driver)(nil),                  // 18: wayfare.Driver
	(*Rider)(nil),                   // 19: wayfare.Rider
	(*Coordinate)(nil),              // 20: wayfare.Coordinate
	(*RideFare)(nil),                // 21: wayfare.RideFare
}
var file_transport_proto_depIdxs = []int32{
	17, // 0: wayfare.TripHistoryResponse.trips:type_name -> wayfare.Trip
	18, // 1: wayfare.DriverProfileResponse.driver:type_name -> wayfare.Driver
	19, // 2: wayfare.RiderProfileResponse.rider:type_name -> wayfare.Rider
	20, // 3: wayfare.PreviewTripRequest.pickup:type_name -> wayfare.Coordinate
	20, // 4: wayfare.PreviewTripRequest.destination:type_name -> wayfare.Coordinate
	21, // 5: wayfare.PreviewTripResponse.ride_fares:type_name -> wayfare.RideFare
	11, // 6: wayfare.TripService.PreviewTrip:input_type -> wayfare.PreviewTripRequest
	13, // 7: wayfare.TripService.StartTrip:input_type -> wayfare.StartTripRequest
	0,  // 8: wayfare.TripService.GetTripDetails:input_type -> wayfare.TripDetailsRequest
	2,  // 9: wayfare.TripService.GetTripHistory:input_type -> wayfare.TripHistoryRequest
	4,  // 10: wayfare.DriverService.GetDriverProfile:input_type -> wayfare.GetProfileRequest
	7,  // 11: wayfare.DriverService.Login:input_type -> wayfare.LoginRequest
	9,  // 12: wayfare.DriverService.Signup:input_type -> wayfare.SignupDriverRequest
	4,  // 13: wayfare.RiderService.GetRiderProfile:input_type -> wayfare.GetProfileRequest
	7,  // 14: wayfare.RiderService.Login:input_type -> wayfare.LoginRequest
	8,  // 15: wayfare.RiderService.Signup:input_type -> wayfare.SignupRiderRequest
	15, // 16: wayfare.PaymentService.InitiatePayment:input_type -> wayfare.InitiatePaymentRequest
	12, // 17: wayfare.TripService.PreviewTrip:output_type -> wayfare.PreviewTripResponse
	14, // 18: wayfare.TripService.StartTrip:output_type -> wayfare.StartTripResponse
	1,  // 19: wayfare.TripService.GetTripDetails:output_type -> wayfare.TripDetailsResponse
	3,  // 20: wayfare.TripService.GetTripHistory:output_type -> wayfare.TripHistoryResponse
	5,  // 21: wayfare.DriverService.GetDriverProfile:output_type -> wayfare.DriverProfileResponse
	10, // 22: wayfare.DriverService.Login:output_type -> wayfare.AuthResponse
	10, // 23: wayfare.DriverService.Signup:output_type -> wayfare.AuthResponse
	6,  // 24: wayfare.RiderService.GetRiderProfile:output_type -> wayfare.RiderProfileResponse
	10, // 25: wayfare.RiderService.Login:output_type -> wayfare.AuthResponse
	10, // 26: wayfare.RiderService.Signup:output_type -> wayfare.AuthResponse
	16, // 27: wayfare.PaymentService.InitiatePayment:output_type -> wayfare.InitiatePaymentResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_transport_proto_init() }
func file_transport_proto_init() {
	if File_transport_proto != nil {
		return
	}
	file_schema_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_transport_proto_goTypes,
		DependencyIndexes: file_transport_proto_depIdxs,
		MessageInfos:      file_transport_proto_msgTypes,
	}.Build()
	File_transport_proto = out.File
	file_transport_proto_goTypes = nil
	file_transport_proto_depIdxs = nil
}
