apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider-service
  template:
    metadata:
      labels:
        app: rider-service
    spec:
      containers:
        - name: rider-service
          image: wayfare/rider-service
          imagePullPolicy: IfNotPresent
          workingDir: /app
          ports:
            - containerPort: 50051
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
            - name: AMQP_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AMQP_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: rider-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 50051
  selector:
    app: rider-service
