apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-service
  template:
    metadata:
      labels:
        app: trip-service
    spec:
      containers:
        - name: trip-service
          image: wayfare/trip-service
          imagePullPolicy: IfNotPresent
          workingDir: /app
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: ENVIRONMENT
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: trip-service
